export const stories = [
  // 1
  {
    title: "Beyond beauty – Joanna",
    paragraphs: [
      "The eyes are one of the greatest gifts to mankind. A gift that allows people to see and appreciate tangible life’s beauty. But the eyes cannot see everything. Ironically, what seems to be the closest can greatly be missed.\n\n18-year old Tiktok influencer Joanna Marie Sisracon has had her fair share of misses. \n\nWhen she was five months old, Joanna got into a fire accident in their house leaving half of her face with severe burns. To her family’s recollection, the fire started when her brother left her alone in their house to do some errands. \n\n“Akala [ni Kuya] po siguro tulog ako no’n, ta’s ibinaba niya malapit sa akin ‘yong gasera. Nagising ako ta’s nadali ko po 'yong gasera, guma-gumapang po ako. Buti nga wala na ko sa kama, kung nasa kama siguro [ako], nakain na rin ako ng foam,” Joanna narrates her life's ordeal.\n\nThis near-death experience left her a scar that she brings up until now. What seemed to be worse is not only her physical scars, but the damages done to her self-image. Growing up, Joanna faced bullies of all sorts because of her appearance. A freak-show for the bullies; a fearsome memory for the young lady.",
      "She even reached the point where she had questioned her mother why they never gave up on her. But like how any mother would respond, she was told: “Kahit ganyan ka, kayang-kaya kitang protektahan.” With such a strong support system, she eventually learned how to cope and move past bad eyes.\n\n“Kaya ko namang protektahan ‘yong sarili ko kasi malaki na po ako, alam ko naman po kung ano ‘yong tama at mali. Do'n sa [mga Tiktok] video [ko], sobrang nakakatulong siya sa’kin kasi doon, nailabas ko ‘yong sarili ko nang walang pag-aalinlangan,” Joanna adds. \n\nThe Joanna that was once afraid to show up grew fierce and proud. Now, she learned to hold her head high with no shame. No more hiding of face. She eventually learned to see herself in high ground and embraced herself to the fullest. \n\nThis young influencer now enjoys creating beauty contents and has used her story to inspire many people to see the beauty in themselves. As of writing, she has 600,000 followers in Tiktok, while her first video went viral with more than 35 million views and still counting. Joanna has captured many people, including one popular cosmetic line.\n\n“Ang masasabi ko lang sa sarili ko, saka sa ibang tao, tanggapin niyo po kung sino at ano kayo bilang kayo. Tayo lang ang tatanggap sa atin at pamilya natin, at pati si Lord na din,” Joanna shares.",
      "She’s still in the process towards achieving her ultimate self. Nonetheless, Joanna has already learned to deal with life’s odd road.\n\n“Na-accept ko ‘yong sarili ko na ganito ako hanggang sa pagtanda, pero may pangarap ako [para sa] sarili ko na baguhin [ang] hitsura ko. Pero ‘yong kalooban ko wala. Kasi kung paano nila ‘ko nakilala, gano'n pa din po nila ako kikilalanin.”",
    ],
    images: [
      "/9degrees-team/1. Joanna/Joanna_1.jpg",
      "/9degrees-team/1. Joanna/Joanna_2.jpg",
      "/9degrees-team/1. Joanna/Joanna_3.jpg",
      "/9degrees-team/1. Joanna/Joana_4.jpg",
      "/9degrees-team/1. Joanna/Joana_5.jpg",
      "/covers/Joanna_cover.jpg",
    ],
  },
  // 2
  {
    title: "A man’s life in between the notes – Ken",
    paragraphs: [
      "Each person has its own sense of purpose. Some people believe that life is best lived with each step taken cautiously, while some choose to take a jump from time to time. But there are only a few who courageously believe that life is best lived on the edge.\n\nKen is one of them.\n\nJohn Kenneth Pimentel, 20, has fallen in love with music ever since he was four. Through the years, he developed good ears for making music. With every beat, his heart dances with the rhythm. Eventually, there is nothing left to see but him, a guitar, and a microphone — for it is mostly through these that he gets a glimpse of life’s hope and consolation.\n\n“Hindi ko na nakikita ‘yong sarili ko bilang ibang tao. Hindi ko na alam ang gagawin ko kung walang music sa akin,” he narrates.\n\nHe started playing the guitar when he was in second grade. His brother taught him, but it was his father that strummed out the musician in him. Some of his icons range from Michael Jackson, Nirvana, Elvis Presley, to OPM bands Eraserheads and She’s Only Sixteen.\n\nHe knew what he wanted to do and who he wanted to be. Even at the sight of death’s door, this is the first thing that came to his mind: “Paano na ‘yong music ko?”",
      "It was a Sunday night and Ken was having fun with some friends. He was a little drunk. He decided to eat lugaw as he’ll have to drive up to the mountain of Marilao. After he drove and left at around 3 AM, all he can remember are fading voices and faint memories.\n\nHe woke up at a hospital room with a damaged hips, injured wrists, and a blood clot on his brain. When he went home from the hospital after a month, Alex Turner was playing on TV and he said to himself: “Ito 'yong mga huli kong tinugtog bago ako ma-aksidente. Hindi na ba ako ulit makapag-gi-gitara?”\n\nThe question made him shrink, but it was the same question that helped him rise — higher, this time.\n\nHe underwent physical therapy for his right hand and while doing that, he taught himself how to play the guitar using his other hand. He didn’t let any excuse kill his dreams in life. He also focused on digital music, specifically Digital Art Workspace. Since he cannot lift any weight or move his right hand, he downloaded different softwares in his phone to, again, create music.\n\nAnd it is with his broken wrist that he has carried greater courage than he has ever held before.\n\n“Isa sa na-realize ko na may pinakamalaking impact sa akin ay ‘do what you love’, kasi hindi natin alam kung kailan tayo mawawala,” he says. He also shared how the incident gave him peace and clarity and that he was humbled enough to now consider other people before doing anything else.",
      "More than ever, Ken knew he needed to continue doing what he loves without fear. After all, he believes that it isn’t about not being afraid, but continuing even if it scares him. It is through this that he has learned to live life to the fullest.\n\nSuccess and fulfillment doesn’t come overnight. Ken still continues to teach himself different kinds of beats, rhythms, and melodies. He is even starting all over again with the guitar. His future is not promised, but nothing matters more now than spending his second life doing what kept him alive for so long.\nAfter all that happened, he remained fearless in pursuit of what keeps his heart burning.",
    ],
    images: [
      "/9degrees-team/2. Ken/Ken_1.jpg",
      "/9degrees-team/2. Ken/Ken_2.jpg",
      "/9degrees-team/2. Ken/Ken_3.jpg",
      "/9degrees-team/2. Ken/Ken_4.jpg",
      "/9degrees-team/2. Ken/Ken_5.jpg",
      "/covers/ken_cover.jpg",
    ],
  },
  // 3
  {
    title: "The sense of service – Renz",
    paragraphs: [
      "More than just a flap of flesh and cartilage on the front of the face, the human nose provides a sense of smell — a powerful tool to sense the spirit of reality. As it draws the ability to bring a sense of security in whiffing an environment, it can also equally invoke a sense of urban filth and misery.\n\nAlong with the high-rise buildings in Manila Bay sits the infamous Smokey Mountain, which was once known as a dumpsite of garbage. While the remnants of wastes remain in the area, its putrid scent has become accustomed to Renz Yumol, a 21-year-old founder of Team Hope Community Outreach Program.\n\nAt a young age, he experienced a myriad of hurdles, from being an adopted child to being exposed to delinquency under the influence of friends.\n\n“I searched myself. Who am I? Sino ba si Renz? Sino ba ako? Wala akong mga magulang, halos naligaw din ako ng landas. Nand’yan ‘yong napasama ako sa mga fraternity, nandiyan ‘yong may mga nagtuturo na magnakaw ka,” he says.\n\nBut, he continued to unravel the facets of his life, and an encounter with an evangelical pastor made him realize his real purpose.\n\n“Then until such time, sabi ko no’n habang nakaupo [ako], may nagsasalita sa harap ko, sabi ko: Lord, gusto ko, ‘yang nagsasalita sa harapan, mas mahigitan ko pa ‘yan. Lord, gusto ko, 'yong kumakain, 'yong nagpapakain, gusto ko maging ganiyan din ako,” Renz recalls.",
      "Bagging the motivation to lift up the younger generation in his community, he established Team Hope Community Outreach Program. Through the generated funding from his friends and donors, they were able to organize projects such as feeding programs, weekly bible study, and sidewalk Sunday school for the children.\n\n“‘Yong mga friends ko sa U.S. [at] sa Australia, nakita nila ‘yong initiative na ‘yon, nagsu-support sila. Then, ‘yong mga iba kong friends sa Federation, ‘yong Federation of Supreme Student Government, ‘yong mga leaders, then ‘yong iba kong mga kapwa-students sa dati kong paaralan, and then ‘yong mga teachers ko, nakikita 'yong ganoon. ‘Yon,  nagsu-support sila, nagbibigay sila until now,” he explains.\n\nEven amid the pandemic, he remained consistent in providing assistance to the communities, most particularly in the Smokey Mountain. Despite the reeking scent of the ground occupied by squatter settlements, he remains zealous in organizing events for the residents, including livelihood programs and water supply.\n\n“No'ng una, siyempre ‘pag sinabi na Smokey Mountain, siyempre… bundok ng basura. Tapos ‘yong toxic doon sa ilalim, malalanghap mo lahat ‘yon. Kaya once na chineck mo ‘yong ilong mo, sobrang kapal ng dumi. Grabe ‘yong dumi.”\n\n“Alam mo, no’ng nagtanong ako [kung] anong pangarap nila paglaki nila? Do’n halos parang bumigay ‘yong pundasyon ko. Sagot sa’kin ng bata, 'Gusto ko po maging snatcher, gusto ko po magnakaw.' Sabi ko (kay) Lord, ‘yon ‘yong isa sa mga nag-pu-pursue sa’kin, talagang nag-uudyok sa’kin na ‘gawin mo na ‘yan, tuloy mo ‘yong naumpisahan mo,’” he adds when asked about his motivation behind the initiative in Smokey Mountain.",
      "He also believes that setting up feeding programs would not be adequate to sustain the needs of the children. For him, they need to be educated and to be instilled with good values.\n\nAlthough there are also hardships in his journey as an advocate, Yumol knows that God guides him in every decision. Moreover, his friends and family support his passion for serving other people.\n\nAt this point, he knows that he has yet to attain his highest form yet. But, he’ll remain to ride on.\n\n“Now, the best version of Renz Yumol, I desire to help more people in my place, other places. I desire to be in a position where I can do anything to help those in need, less fortunate,” he said.",
    ],
    images: [
      "/9degrees-team/3. Renz/Renz_1.jpg",
      "/9degrees-team/3. Renz/Renz_2.jpg",
      "/9degrees-team/3. Renz/Renz_3.jpg",
      "/9degrees-team/3. Renz/Renz_4.jpg",
      "/9degrees-team/3. Renz/Renz_5.jpg",
      "/covers/Renz_cover.jpg",
    ],
  },
  // 4
  {
    title: "Feeding one’s soul – Mich",
    paragraphs: [
      "“Kung kami nagtitipid [na] nang ganito, paano pa ‘yong ibang tao sa labas na wala namang stable na trabaho?”\n\nGetting through the pandemic, people from different communities and walks of life struggled to make ends meet, trying hard to put food on their table. Payatas Community Pantry organizer and Polytechnic University of the Philippines alumna, Michelle Ann Morales had realized the need to extend help in these times. \n\nGrowing up, this young leader already got exposed to volunteering and community work. At the age of 13, she started serving as a church volunteer, Sunday school teacher, and feeding program helper — something she still does until today. \n\nEnter pandemic. What used to be a seasonal deed became a regular one.\n\nEverything started by knowing and hearing the struggles people experience on the ground through her father. “Nakausap niya [her father] ‘yong mga nagbabantay na nawalan ng trabaho. Nakuwento niya ‘yong mga pahinante, mga driver, 200 in a week ang kinikita, pero marami doon maraming anak. Parang hindi enough ang 200 pesos para mabuhay ka sa isang linggo,” she recalled.\n\nWhen Mich heard of Ana Patricia Non’s Maginhawa Community Pantry, she decided to do it in her area, bringing with her the stories of people like those her father told about.\n\nShe connected with people around her community, gathering more volunteers and supplies.\n\nFrom three volunteers, it grew to more than 40 people from different areas and neighborhoods. They even connected with other community pantries. Also, Mich started a community kitchen, filling more stomachs across the town.",
      "Alas, a movement ignited by hunger for those in hunger evolved in Payatas, Quezon City.\n\n“So, 'di ko rin ine-expect… akala mo ikaw lang ‘yong nakakakita pero ang dami palang taong gustong tumulong,” she said. \n\nHowever, Mich noted that there were people who saw the pantry as a form of ‘ayuda’. But she eagerly educated them that pantries are products of collective work from the community members, stressing that pantries are not initiatives of the government.\n\nMich and the pantry had no break since April 18, 2021. She initially planned to keep the pantry open for just a month, but as more people donated and asked for help, she marched forward. Even during her personal affairs, the pantry still shows up.\n\nRight now, she is finishing her Master of Science in Industrial Relations Management. Afterwards, she still plans to take another course as she loves studying. Nevertheless, like how she was taught before, everything Mich does is still rooted in helping and meeting people.\n\n“Hindi ka lang natututo sa books, natututo ka rin sa mga tao sa paligid mo,” she explained.\n\nRight now, aside from her community work, she also connects with her church and other organizations like Lilok Foundation. In her free time, like anyone else, she feeds her soul by doing hobbies like cooking, baking, and sewing.",
      "As a young individual, Mich knows that she’s still miles away from her best form yet.\n\n“Naniniwala ako na marami pa akong magagawa at marami pa akong ma-aachieve dahil sa inspiration na nakukuha mo doon sa mga tao sa paligid mo. Sabi nga nila, everyday, marami kang natututunan.”\n\nFor Mich, helping others is already a way of life; and its fruits are enough to satisfy a soul’s hunger. The joy and gratefulness other people express once they receive help is the tastiest treat life can offer.",
    ],
    images: [
      "/9degrees-team/4. Mich/Mich_1.jpg",
      "/9degrees-team/4. Mich/Mich_2.jpg",
      "/9degrees-team/4. Mich/Mich_3.jpg",
      "/9degrees-team/4. Mich/Mich_4.jpg",
      "/9degrees-team/4. Mich/Mich_5.jpg",
      "/covers/Mich_cover.jpg",
    ],
  },
  // 5
  {
    title: "The art of purpose - Albert",
    paragraphs: [
      "“I find making artworks as my love language.”\n\nHands do work in pairs. Taking shower, cooking food, or playing sports — all demand the coordination of both hands. But, Albert Raqueño dares to be different. One hand he extends to himself, the second towards others.\n\nAlbert, a 22-year-old visual artist from UP College of Fine Arts, uses his skills both for self-expression and political protest.\n\n“I find creating as my language to communicate what I think should be communicated,” he said. “Sometimes it might be personal, sometimes [about] mental health. Sometimes, it’s also about whatever’s going on here in the country or whatever social issue I want to address.”\n\n Albert is the artist behind the prominent artworks dedicated for progressive politicians, such as Vice President Leni Robredo, Senator Kiko Pangilinan, and Kabataan Party-List Rep. Sara Elago. For him, art is political as it is personal.\n\n“The moment that we try to separate personal from political, I think that only gives off some sort of selfishness or a high horse,” adds Albert. “So we try to use whatever skills we have for the better, not just for ourselves.”",
      "He uses both digital and traditional art for his masterpieces. In traditional art, he does paint his artworks using gouache, acrylic, and even watercolor, especially for sceneries and landscapes. He also does live-sketching using ink. While digital allows him to work faster, in traditional [form], he finds his artworks more vulnerable, intimate, and raw.\n\nFor Albert, art and himself can never be separated. The feelings and energy in which he invests every time he decides to create, may it be single or collaboration, are so powerful that he and his artwork become one.\n\n“May it be personal projects or perhaps collaborations, I see it as ‘working with’ not ‘working for.’ It’s like when you work artist to artist, there is really a lot of life to put into your work. And that’s what really gives me some sort of fulfillment.”\n\nHis mom, who was a Fine Arts student back then, and his older sister who is also an artist, have been an important influence on his artistic interests. Until the time came when he pursued art on his own, getting first into UST Fine Arts, before moving to UP.\n\nIn UP, he found his purpose to continue doing his passion. There he met people who inspired him to do and be good, allowing him to stretch himself beyond limits. “I think my milestone was when I created artworks for UP Fair Hiwaga in 2020. It was a dream come true,” he says with a big smile.",
      "As perfect as an artist one may perceive him, Albert has his own shortcomings. Academic duties, art commissions, and peer pressure – all make him question his own art works sometimes.\n\n“I set my standards high for myself. So sometimes it’s inevitable that I ask myself, ‘What if this way?’ ‘What if I could have done better?’ “Or what if I was in a different state?’' says Albert, pointing out that in the end we have nothing but ourselves who can pick us up. “As long as we are doing our best, we are not consumed by bad intentions or pride or whatever else [that are] negative.”\n\nDoing the things he always loved, having people who love and support him — all while living on his own — Albert knows that he still has a lot to achieve. For him, he’s just starting to allow himself to feel the best of feelings and process all he has done through. After all, he is just “a person who tries.”\n\n“Right now, I’m acknowledging that I should take steps to breathe. To take my time and to process my own feelings, to come back stronger and to avoid being burned out. As for the ‘best version’ of myself now, I think, no[t yet]. But, I am on the way.”",
    ],
    images: [
      "/9degrees-team/5. Albert/Albert_1.jpg",
      "/9degrees-team/5. Albert/Albert_2.jpg",
      "/9degrees-team/5. Albert/Albert_3.jpg",
      "/9degrees-team/5. Albert/Albert_4.jpg",
      "/9degrees-team/5. Albert/Albert_5.jpg",
      "/covers/albert_cover.jpg",
    ],
  },
  // 6
  {
    title: "Realized reality - Hayme",
    paragraphs: [
      "Upon using all of the senses to experience the stories of the people, how could one not act?\n\nTo witness, hear, smell, touch, and have a taste of another’s aching reality, it’s inevitable to help — this is how Hayme Alegre described his motivation to keep on serving the people.\n\nHayme, 22, an alumnus of the Polytechnic University of the Philippines (PUP), is a national Tulong Kabataan (TK) Volunteer Network coordinator. Given his organization’s nature of work, he has been involved in a lot of relief operations and rehabilitative aids throughout the pandemic.\n\nHis humanitarian work journey started through his political and academic organizations in PUP such as Sandigan ng Mag-aaral para sa Sambayanan (SAMASA) and Bukluran sa Sikohiyang Pilipino, which holds series of community immersions and outreach programs.\n\nHis passion to lend a helping hand intensified when the TK- Sta. Mesa revived their organization to initiate the call for donations for the affected communities of the Taal eruption in February 2020. Then, came the COVID-19 pandemic which made a lot more Filipinos to suffer and cry for help.\n\n“It's high-time rin, eh, na makiisa kasi nasa surge na tayo ng malawak na pandemyang hindi matapos-tapos. ‘Yong mga tao nawawalan ng trabaho, maraming nawalan ng kabuhayan, gan’yan. So, parang ano talaga siya, it’s now or never, na parang it’s now na sasali ka or never ka na makikiisa,” Hayme narrated the urgency to help one another.",
      "Subsequently, he moved up to the national chapter of Tulong Kabataan. There, his scope of work broadened, but he continued to organize donation drives, relief operations, and community immersions.\n\n“Aside doon sa pagbibigay ng relief, inaalam natin ‘yong kalagayan ng communities, inaalam natin, nakikiisa tayo doon sa mga panawagan para sa solusyon kasi sa totoo lang naman, ‘yong mga relief na pinapamigay natin hindi siya sustainable,” he elaborates how amplifying the people’s voices is part of his mission too.\n\nCalls for accountability, cash assistance, academic break, better pandemic and calamity response are some of the localized campaigns his organization is still doing to assert the rights of certain communities.\n\nHayme shared that one of the hardest challenges of being a humanitarian worker is witnessing how some communities would lose hope through the process.\n\n“Sa panahon kasi na ‘di siya agad nangyayari, siyempre nakaka-demoralize siya. Tapos, hardest part is makita sila [‘yong community] na unti-unti na rin silang nanghihina,” he narrates.\n\nImmersing in other people’s lives drives Hayme with mixed emotions. Bringing smiles to their faces and knowing they remember him warms his heart. On the other hand, realizing how much they are struggling wakes him up from his reverie and reminds them of how much help they need.",
      "Looking back years ago, he admitted that he was once out of touch from the material conditions that people were actually facing. “I’m really out of touch, sa totoo lang. Tapos noong nag-SAMASA ako, it turned out na it’s really different from what we’ve been seeing sa mass media, sa iba’t iba pang platforms.”\n\nBut upon pondering his own contradictions, he listened to the people’s voices, touched their hands that had already suffered much, saw their tired yet hopeful smiles, and smelled the rotten system that caged them, there he had a taste of the true reality. All of those factors led him to where he is right now — a humble yet courageous humanitarian worker and activist.\n\n“If your heart goes out to serving people and the fire to continue is within you, then go. As long as you’re for the people, you should continue on.”",
    ],
    images: [
      "/9degrees-team/6. Hayme/Hayme_1.jpg",
      "/9degrees-team/6. Hayme/Hayme_2.jpg",
      "/9degrees-team/6. Hayme/Hayme_3.jpg",
      "/9degrees-team/6. Hayme/Hayme_4.jpg",
      "/9degrees-team/6. Hayme/Hayme_5.jpg",
      "/covers/haymer_cover.jpg",
    ],
  },
  // 7
  {
    title: "A ‘conscious’ warrior in scrubs – Jan",
    paragraphs: [
      "The young, scholarly graduate could pass for any person who has a good head on their shoulders.\n\nDressed in his scrubs for his NIH COVID-19 Task Force volunteer work, Jan Mickaele de Leon sauntered his way to UP Manila with his chin held high and heart filled with purpose. He welcomed the challenge of helping people despite being in lockdown. He was the epitome of a person right on track in life.\n\nBehind closed doors, however, during breaks or in-betweens, were anxiety attacks that came more often than he would like — a subconscious effort of the mind in wracking his whole being.\n\nJan was diagnosed with Manic Bipolar Type 2 Disorder in 2017. It began with the constant bouts of anxiety and depression he felt the year before. “The panic and anxiety attacks started when my mother died last November 2016. I remember waking up in hospital beds or in a clinic. An oxygen mask was often on my face, and a lot of needles stuck in my arms,” Jan explains.\n\nUntil now, he is undergoing constant therapy with his psychiatrist, one of the two he had since his diagnosis, and also the one who re-diagnosed him with General Anxiety Disorder.\n\n“I am not my mental illness though,” Jan exclaimed.",
      "Despite his diagnosis, he forged his own path towards finding himself, trying out a lot of sidelines to earn a living. He went from being a Starbucks barista to being Pru Life’s License Finance Adviser. He also took on administrative and call center jobs in between. He’s tried it all. Or at least he thought he did, until he was given the chance to be a frontliner last 2020.\n\nWorking for supplies and equipment in UP Manila was not easy, especially in the early months of the pandemic. “In those first three months [of lockdown] inside UP, there is this constant fear of not knowing when you could get infected.”\n\nFear was a factor in the many attacks he has experienced during said lockdown. Still, he wouldn’t have it any other way, finding the whole experience “fulfilling” and “of service to the country.”\n\n“After being lost, with my illness and all the things going on in my life, I found my purpose,” says Jan.",
      "Even with his purpose in the forefront of his mind, Jan believes that he has yet to be the best version of himself. “But, looking back at my journey, I can definitely say that I am better than the Jan Mickaele before,” he adds.\n\nHe wouldn’t have the strength to move forward if it wasn’t for his friends and loved ones. Whether in the form of quality time with friends, a walk on a beach to hear the sound of the sea, or through a strong support system at work, Jan walks an endless labyrinth of comfort and safe space.\n\nIn what seems to be one heck of a ride of events and attacks, Jan carried on. Despite his mental illness — just there in the background, in the subconscious of his mind, he worked, volunteered, and steered steadily forward.\n\n“I am not my mental illness,” reiterated Jan. “I am a warrior. I am me.”",
    ],
    images: [
      "/9degrees-team/7. Jan/Jan_1.jpg",
      "/9degrees-team/7. Jan/Jan_2.jpg",
      "/9degrees-team/7. Jan/Jan_3.jpg",
      "/9degrees-team/7. Jan/Jan_4.jpg",
      "/9degrees-team/7. Jan/Jan_5.jpg",
      "/covers/Jan_cover.jpg",
    ],
  },
  // 8
  {
    title: "A gift who gives back – Carl",
    paragraphs: [
      "Giving back is perhaps the most expensive thing in the world. Anyone can receive anything from anybody. But, not all can afford to give — especially without expecting in return.\n\nCarl Angelo Espiritu, 25, chooses the path most people of his generation dare not to choose.\n\nNow serving as one of the council advisers for Guiguinto Scholars’ Association (GSA), a non-profit organization that offers scholarships to students, he inspires youth to become not just academic achievers but also leaders they are expected to be.\n\n“I started when I was in third year high school. Half of my life has already been devoted to volunteering,” said Carl. “I only joined seminars or workshops that GSA was organizing. Then I saw how welcoming the organization is. They felt like family.”\n\nGSA organizes workshops, seminars, training, competitions, and more to run and fund its scholarship program. It aims to redefine the purpose of a ‘scholar,’ believing that one should possess not only intelligence, but also desire to serve the community.\n\nCarl learned a lot from these workshops and activities, eventually becoming an officer, then president. It is in this part where he grew as a person, for he learned things he could not get in classrooms. “I realized I can make a difference in my own little way through different projects by simply doing my job, my task.”",
      "Carl always knew that choosing the path of volunteerism would cost him time, energy, and even money. But, it has never stopped him from walking on this path. In fact, this is only where he receives the fulfillment he doesn’t get from any type of job.\n\n“I thought I was giving hope to people, that I [would] empower them. But, that’s the exact opposite. They encourage me to continue, to be a better person, and to give and give what you have,” he says. “It seems they are the ones who give you a sense of purpose – to continue and move forward, to do more.”\n\nCarl’s presidency ended, and he needed to find a job. Graduating with a degree in Mass Communication, he started his first job as a researcher in GMA News and Public Affairs. He was sure then that this was the best career for him. He worked hard and paved his own way to success.\n\nThen, the time came when he could no longer find the same spark of joy he once had experienced. He was unsatisfied. He was looking for something, so he quit his job.\n\nThere he found a job that shares his passion in community development.\n\n“It’s a BPO company in general and what we specifically do is help our employees continue their education while working. The company is sponsoring a very big chunk of support for their studies. So that’s our commitment, to help employees continue the things they have been deprived of while they’re not still our employees,” recalls Carl.",
      "In it, he again finds the purpose and duty to give back to the people. It’s like hitting three birds with one stone. He can work, study, and help others — all at the same time. Carl is now taking up Masters in Community Development at UP Diliman.\n\n“I love development works, so I continue working here. I’m now turning four years, and I realize I want to deepen my knowledge about community work. Here, I can study while working. And at the same time I can still participate in community works during my weekends and free time,” adds Carl.",
    ],
    images: [
      "/9degrees-team/8. Carl/Carl_1.jpg",
      "/9degrees-team/8. Carl/Carl_2.jpg",
      "/9degrees-team/8. Carl/Carl_3.jpg",
      "/9degrees-team/8. Carl/Carl_4.jpg",
      "/9degrees-team/8. Carl/Carl_5.jpg",
      "/covers/carl_cover.jpg",
    ],
  },
  // 9
  {
    title: "Onwards, Forward – You",
    paragraphs: [
      "Wisdom, being the highest level of consciousness, is only obtained by tapping into every challenge and victory a person experiences. One may find it in the midst of their despair, others might see it in the light of day. This is something that You, a youth, has realized over time.\n\nYou is someone who strives to do better each day. Like the other eight youths, You have already had a lifetime of pains and strength, tears and laughter, and failures and successes. Each day for You is a day for growth.\n\nYou is like Joanna, who is on the way to pure self acceptance. You also lived like Ken and Albert, who have realized the power of the gifts they hold. You also took the path taken by Renz, Mich, Carl, Jan and Hayme who decided to extend their arms and warm hands to others.\n\nLike every youth out there, You is in constant pursuit of change and enlightenment. As each day passes, they take one step towards their supreme value. Little by little, they develop unwavering confidence, having the guts to face any obstacle and bumps life would leave on the trail they take.\n\nEach day, they try to change the world, one step at a time. You, at a young age, didn’t need to take ten lifetime miles to understand the world; the nine bumpy roads one moved past have taught them already the very essence of life.\n\nYou is still on a trip, enjoying the sceneries of realities and dreams at the side, while looking forward to the boundless possibilities the long road may lead them.\n\nYou. You are onto your highest form yet. Hang on and enjoy the ride",
    ],
  },
];
